keys:
  - &primary age1z38q08es3vmn8enk7zjzcvekp23698u9l5dxkgjch2y6lc3h09jsf7kfas
  - &svr1 age1hrtk8mjh9krsqk8k65ztkyeqwaju3elgka83dufy5gdm0vu0ygqq0xkj25
  - &tyo2 age12ryhr9lh6u42ergen7k4f4c79pdk6rqgrly6um5yyfxlj062g3lsm2ljh2
  - &nah0 age1skg3exn8yjve0zczv7p4sqyfscryaff7vj2gtf77pr3djfperf0qp9n9lj
  - &nium0 age153xw92hlng0r480fuxuf34legj2h9x2y0l9dshht39fh7mhx7pks6r3wkg
  - &tyo3 age1en8fcu353gtyutj22x2kuyy7xt9a90rrqhnp60c06sdpgcp4tgxsm8347d
  - &fra0 age1yc4x9hn4f86lagcgvqu5h4aavm50w7sdfmhsv3nk7t5te9zwjczswd2y47

creation_rules:
  - path_regex: hosts/svr1/.*
    key_groups:
    - age:
      - *primary
      - *svr1
  - path_regex: hosts/tyo2/.*
    key_groups:
    - age:
      - *primary
      - *tyo2
  - path_regex: hosts/fra0/.*
    key_groups:
    - age:
      - *primary
      - *fra0
  - path_regex: modules/.*
    key_groups:
    - age:
      - *primary
      - *svr1
      - *tyo2
      - *nah0
      - *nium0
      - *tyo3
      - *fra0
  - path_regex: hosts/nium0/.*
    key_groups:
    - age:
      - *primary
      - *nium0
  - path_regex: hosts/nah0/.*
    key_groups:
    - age:
      - *primary
      - *nah0
  - path_regex: hosts/tyo3/.*
    key_groups:
    - age:
      - *primary
      - *tyo3
