name: Colmena
on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'Git Ref to Deploy'
        required: true
        default: 'refs/heads/primary'

jobs:
  deploy:
    environment: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: '${{ inputs.ref }}'
    - uses: cachix/install-nix-action@v17
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Print nixpkgs version
      run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    # - name: Check format
    #   run: nix-shell -p nixpkgs-fmt --run "nixpkgs-fmt --check ./"
    # - name: "Test build"
    #   run: nix-shell -p colmena --run "colmena build"
    - uses: shimataro/ssh-key-action@v2
      with:
        key: '${{ secrets.SSH_PRIV_KEY }}'
        known_hosts: ${{ secrets.KNOWN_HOSTS }} # Not secret at all, just make it easier to change
    - name: "Do deploy"
      run: nix-shell -p colmena --run "colmena apply"
